spring:
  application:
    name: content-droid
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:content-droid}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    queue-name: ${RABBITMQ_QUEUE_NAME:videos}
